### ISSUE TITLE
Are you looking for contributors?

### ISSUE THREAD

**Issue by srcwhitaker** [jjmontesl/cubetl#11]
We're looking for a project that we can build upon to ETL and visualize Real Estate Data. Also allowing CRUD functionality in regards to Create/Update Dimensions and creating custom ranges with Filters at a user level. If we started a proof of concept using cubetl, would we be able to get support to our questions?

**Comment by jjmontesl** [comment]
Hi. I answer issues here and dispatch pull requests, but the frequency varies. My main focus is set on another area currently. Yes I'd like to push this project and I do use it myself for some data transformation pipelines (incidentally I'll be pushing some commits later today).

I think however that this project needs some architecture-level discussion and I'd like to tackle that as it's unclear what direction and scope it should pursue, in order to serve beyond being an experimental tool. I'm curious as to what usage you have in mind.

If you wish to discuss your particular use case, feel free to drop me an email.
